name: phpstan

on:
  workflow_dispatch:

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run PHPStan
        run: composer analyse
